const { chromium } = require(process.env.DOCGOV_PLAYWRIGHT_PACKAGE || 'playwright');
const { execFileSync } = require('node:child_process');

const root = require('node:path').resolve(__dirname, '..');
const php = process.env.DOCGOV_PHP || 'php';
const base = process.env.DOCGOV_TEST_BASE_URL || 'http://localhost:8000';
const chrome = process.env.DOCGOV_BROWSER_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const runPhp = code => execFileSync(php, ['-r', code], { cwd: root, encoding: 'utf8' }).trim();
const assert = (value, message) => { if (!value) throw new Error(message); };
const session = runPhp(`
require 'config/db.php';
$user = $pdo->query("SELECT id, name, username, email, role, active FROM users WHERE role = 'admin' AND active = TRUE ORDER BY id LIMIT 1")->fetch(PDO::FETCH_ASSOC);
if (!$user) throw new RuntimeException('Administrador de teste indisponível.');
$sessionId = bin2hex(random_bytes(16));
session_id($sessionId); session_start();
$_SESSION['user'] = ['id' => (int)$user['id'], 'nome' => $user['name'], 'login' => $user['username'], 'email' => $user['email'], 'role' => $user['role'], 'active' => true, 'inicial' => mb_substr($user['name'], 0, 1)];
$_SESSION['admin_logged'] = true; session_write_close();
echo $sessionId;
`);

(async () => {
  let mediaId = 0;
  const browser = await chromium.launch({ headless: true, executablePath: chrome });
  try {
    const context = await browser.newContext();
    await context.addCookies([{ name: 'PHPSESSID', value: session, url: base }]);
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const response = await page.goto(`${base}/admin/index.php?tab=novo_documento&action=edit_doc&id=169`, { waitUntil: 'domcontentloaded' });
    assert(response?.status() === 200, `Editor HTTP ${response?.status()}`);
    assert(await page.locator('#quill-editor-container .ql-editor').count() === 1, 'Quill não iniciou.');
    assert(await page.locator('#article-insert-image').isVisible(), 'Ferramenta de imagem não aparece.');
    const legacy = await page.evaluate(() => GovDocArticleMedia.normalizeLegacyHtml('<p><img src="../document-media.php?id=9" alt="Antiga"></p><p><em>Legenda antiga</em></p>'));
    assert(legacy.includes('<figure') && legacy.includes('<figcaption>Legenda antiga</figcaption>'), 'Conteúdo antigo não foi adaptado ao bloco móvel.');
    const legacyVideo = await page.evaluate(() => GovDocArticleMedia.normalizeLegacyHtml('<iframe class="ql-video" src="https://www.youtube-nocookie.com/embed/tvnAs_Y0VT8"></iframe>'));
    assert(legacyVideo.includes('<figure') && legacyVideo.includes('govdoc-media'), 'Vídeo antigo não foi adaptado ao bloco móvel.');
    const legacyInline = await page.evaluate(() => GovDocArticleMedia.normalizeLegacyHtml('<p>Antes <img src="../document-media.php?id=9" alt="Antiga"> depois</p>'));
    assert(legacyInline.includes('</p><figure') && legacyInline.includes('</figure><p> depois</p>'), 'Imagem antiga no meio do texto não foi separada sem perder as frases.');
    const legacyLayout = await page.evaluate(() => {
      const host = document.createElement('div'); document.body.append(host);
      const editor = new Quill(host, { theme: 'snow' });
      editor.clipboard.dangerouslyPasteHTML('<figure class="govdoc-media govdoc-media--block-left" style="width: 40%"><img src="../document-media.php?id=9" alt="Antiga"></figure>', 'silent');
      const layout = editor.root.querySelector('figure.govdoc-media')?.className || '';
      host.remove(); return layout;
    });
    assert(legacyLayout.includes('govdoc-media--wrap-left'), 'Layout antigo não foi convertido para Texto à direita no editor.');
    await page.evaluate(() => {
      const editor = Quill.find(document.getElementById('quill-editor-container'));
      editor.setText('Antes da mídia aqui\nSegundo parágrafo\nTerceiro parágrafo\n', 'silent');
      editor.setSelection(8, 0, 'user');
    });
    await page.locator('#article-image-alt').fill('Imagem do teste de artigo');
    await page.locator('#article-image-caption').fill('Legenda de teste');
    const tinyPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WlOdbsAAAAASUVORK5CYII=', 'base64');
    await page.locator('#article-image-file').setInputFiles({ name: 'exemplo.png', mimeType: 'image/png', buffer: tinyPng });
    await page.locator('#article-media-status').filter({ hasText: 'Imagem inserida' }).waitFor({ timeout: 15000 });
    const image = page.locator('#quill-editor-container .ql-editor img[src*="document-media.php?id="]').last();
    assert(await image.count() === 1, 'Imagem não foi inserida no corpo do artigo.');
    assert(await image.getAttribute('alt') === 'Imagem do teste de artigo', 'Texto alternativo não foi aplicado.');
    const figure = page.locator('#quill-editor-container .ql-editor figure.govdoc-media').last();
    assert(await figure.count() === 1, 'Imagem e legenda não foram agrupadas em um bloco móvel.');
    assert((await figure.locator('figcaption').innerText()) === 'Legenda de teste', 'A legenda não acompanha a imagem.');
    const neighbors = await figure.evaluate(node => ({ before: node.previousElementSibling?.textContent || '', after: node.nextElementSibling?.textContent || '' }));
    assert(neighbors.before.includes('Antes da') && neighbors.after.includes('mídia aqui'), `Inserção não respeitou o cursor: ${JSON.stringify(neighbors)}`);
    const source = await image.getAttribute('src');
    mediaId = Number(new URL(source, page.url()).searchParams.get('id'));
    assert(mediaId > 0, 'ID da imagem inválido.');
    await image.click();
    assert(await page.locator('#article-selected-media').isVisible(), 'Painel de posição da mídia não abriu.');
    assert((await page.locator('[data-media-layout]').allTextContents()).join('|') === 'Centro|Texto à direita|Texto à esquerda', 'Painel ainda oferece esquerda/direita sem contorno de texto.');
    await figure.screenshot({ path: 'tmp/article-resize-handles.png' });
    await figure.locator('.govdoc-media-resize-handle--se').scrollIntoViewIfNeeded();
    const centerHandle = await figure.locator('.govdoc-media-resize-handle--se').boundingBox();
    const centerStartX = centerHandle.x + centerHandle.width / 2;
    const centerStartY = centerHandle.y + centerHandle.height / 2;
    await page.mouse.move(centerStartX, centerStartY);
    await page.mouse.down();
    await page.mouse.move(centerStartX - 35, centerStartY, { steps: 4 });
    await page.mouse.up();
    const centerWidth = Number((await figure.getAttribute('style')).match(/width:\s*(\d+)%/)?.[1]);
    assert(centerWidth < 80, `Arrastar o canto de uma imagem centralizada não alterou a largura: ${JSON.stringify({ centerHandle, centerWidth, status: await page.locator('#article-media-status').innerText() })}`);
    await page.locator('[data-media-layout="wrap-left"]').click();
    assert(await figure.getAttribute('class').then(value => value.includes('govdoc-media--wrap-left')), 'Contorno de texto não aplicado.');
    assert((await figure.getAttribute('style')).includes('width: 50%') && (await page.locator('[data-media-width]').getAttribute('max')) === '50', 'Prévia e controle de largura divergiram no contorno do texto.');
    await page.locator('[data-media-width]').evaluate(input => { input.value = '45'; input.dispatchEvent(new Event('input', { bubbles: true })); input.dispatchEvent(new Event('change', { bubbles: true })); });
    assert((await figure.getAttribute('style')).includes('width: 45%'), 'Largura não atualizada na prévia.');
    const beforeResizePixels = await figure.evaluate(node => node.getBoundingClientRect().width);
    await figure.locator('.govdoc-media-resize-handle--se').scrollIntoViewIfNeeded();
    const resizeBox = await figure.locator('.govdoc-media-resize-handle--se').boundingBox();
    assert(resizeBox, 'A alça de redimensionamento não apareceu na imagem.');
    const resizeX = resizeBox.x + resizeBox.width / 2;
    const resizeY = resizeBox.y + resizeBox.height / 2;
    await page.mouse.move(resizeX, resizeY);
    await page.mouse.down();
    await page.mouse.move(resizeX - 70, resizeY, { steps: 6 });
    const previewWidth = Number((await figure.getAttribute('style')).match(/width:\s*(\d+)%/)?.[1]);
    assert(previewWidth >= 25 && previewWidth < 45, `Arrastar a alça não atualizou a prévia (${previewWidth}%).`);
    assert((await figure.evaluate(node => node.getBoundingClientRect().width)) < beforeResizePixels, 'A imagem não diminuiu visualmente durante o arraste.');
    assert((await page.locator('[data-media-width-output]').innerText()) === `${previewWidth}%`, 'Indicador de largura não acompanha o redimensionamento.');
    await page.mouse.up();
    const resizedWidth = Number((await figure.getAttribute('style')).match(/width:\s*(\d+)%/)?.[1]);
    assert(resizedWidth === previewWidth, 'Largura mudou ao terminar o redimensionamento.');
    assert((await figure.locator('.govdoc-media-resize-handle').count()) === 4, 'A imagem não mostra os quatro pontos de redimensionamento.');
    const ratioBefore = await figure.locator('img').evaluate(image => image.getBoundingClientRect().width / image.getBoundingClientRect().height);
    await figure.locator('.govdoc-media-resize-handle--nw').scrollIntoViewIfNeeded();
    const oppositeBox = await figure.locator('.govdoc-media-resize-handle--nw').boundingBox();
    await page.mouse.move(oppositeBox.x + oppositeBox.width / 2, oppositeBox.y + oppositeBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(oppositeBox.x + oppositeBox.width / 2 - 30, oppositeBox.y + oppositeBox.height / 2, { steps: 5 });
    await page.mouse.up();
    const cornerWidth = Number((await figure.getAttribute('style')).match(/width:\s*(\d+)%/)?.[1]);
    assert(cornerWidth > resizedWidth, 'O canto superior esquerdo não ampliou a imagem.');
    const ratioAfter = await figure.locator('img').evaluate(image => image.getBoundingClientRect().width / image.getBoundingClientRect().height);
    assert(Math.abs(ratioAfter - ratioBefore) < .01, 'Redimensionamento distorceu a proporção da imagem.');
    let finalWidth = cornerWidth;
    for (const [corner, delta, grows] of [['ne', 22, true], ['sw', 22, false]]) {
      const handle = figure.locator(`.govdoc-media-resize-handle--${corner}`);
      await handle.scrollIntoViewIfNeeded();
      const box = await handle.boundingBox();
      const x = box.x + box.width / 2;
      const y = box.y + box.height / 2;
      await page.mouse.move(x, y);
      await page.mouse.down();
      await page.mouse.move(x + delta, y, { steps: 4 });
      await page.mouse.up();
      const nextWidth = Number((await figure.getAttribute('style')).match(/width:\s*(\d+)%/)?.[1]);
      assert(grows ? nextWidth > finalWidth : nextWidth < finalWidth, `O canto ${corner} não redimensionou a imagem.`);
      finalWidth = nextWidth;
    }
    await page.locator('[data-media-caption]').fill('Legenda ajustada');
    await page.locator('[data-media-caption]').press('Tab');
    assert((await figure.locator('figcaption').innerText()) === 'Legenda ajustada', 'Legenda não atualizada na prévia.');
    const beforeMove = await page.evaluate(() => { const q = Quill.find(document.getElementById('quill-editor-container')); return q.getIndex(Quill.find(q.root.querySelector('figure.govdoc-media'))); });
    await page.evaluate(() => { window.__mediaDragEvents = []; for (const name of ['dragstart', 'dragover', 'drop', 'dragend']) document.addEventListener(name, event => { const caret = document.caretRangeFromPoint?.(event.clientX, event.clientY); const blot = caret && Quill.find(caret.startContainer, true); const q = Quill.find(document.getElementById('quill-editor-container')); window.__mediaDragEvents.push(`${name}:${event.target.tagName}.${event.target.className}:${blot?.statics?.blotName || ''}:${blot ? q.getIndex(blot) + caret.startOffset : ''}`); }, true); });
    await figure.locator('.govdoc-media-handle').dragTo(page.locator('#quill-editor-container .ql-editor p').first(), { targetPosition: { x: 2, y: 8 } });
    const afterMove = await page.evaluate(() => { const q = Quill.find(document.getElementById('quill-editor-container')); return q.getIndex(Quill.find(q.root.querySelector('figure.govdoc-media'))); });
    const dragDetails = await page.evaluate(() => ({ events: window.__mediaDragEvents, draggable: document.querySelector('#quill-editor-container .ql-editor figure.govdoc-media')?.getAttribute('draggable'), status: document.getElementById('article-media-status')?.textContent, children: Array.from(document.querySelector('#quill-editor-container .ql-editor').children).map(node => `${node.tagName}:${node.textContent.slice(0, 30)}`) }));
    assert(afterMove < beforeMove, `Arrastar não reposicionou o bloco (${beforeMove} → ${afterMove}): ${JSON.stringify(dragDetails)}`);
    await page.locator('[data-media-move="down"]').click();
    const afterKeyboardMove = await page.evaluate(() => { const q = Quill.find(document.getElementById('quill-editor-container')); return q.getIndex(Quill.find(q.root.querySelector('figure.govdoc-media'))); });
    assert(afterKeyboardMove > afterMove, 'Botão de mover abaixo não reposicionou o bloco.');
    await page.locator('[data-media-move="up"]').click();
    const editorRoot = page.locator('#quill-editor-container .ql-editor');
    await figure.locator('.govdoc-media-handle').scrollIntoViewIfNeeded();
    let rootBox = await editorRoot.boundingBox();
    let moveBox = await figure.locator('.govdoc-media-handle').boundingBox();
    let moveX = moveBox.x + moveBox.width / 2;
    let moveY = moveBox.y + moveBox.height / 2;
    await page.mouse.move(moveX, moveY);
    await page.mouse.down();
    await page.mouse.move(rootBox.x + rootBox.width * .84, moveY, { steps: 8 });
    assert((await page.locator('.govdoc-media-drop-zones').getAttribute('data-active-layout')) === 'wrap-right', 'Arraste não destacou a zona Texto à esquerda.');
    await page.screenshot({ path: 'tmp/article-layout-drop-zones.png' });
    await page.mouse.up();
    assert((await figure.getAttribute('class')).includes('govdoc-media--wrap-right'), 'Soltar à direita não colocou o texto à esquerda.');
    await image.scrollIntoViewIfNeeded();
    rootBox = await editorRoot.boundingBox();
    const imageBox = await image.boundingBox();
    await page.mouse.move(imageBox.x + imageBox.width / 2, imageBox.y + Math.min(45, imageBox.height / 2));
    await page.mouse.down();
    await page.mouse.move(rootBox.x + rootBox.width / 2, imageBox.y + Math.min(45, imageBox.height / 2), { steps: 8 });
    assert((await page.locator('.govdoc-media-drop-zones').getAttribute('data-active-layout')) === 'center', 'Arrastar a própria imagem não destacou a zona central.');
    await page.mouse.up();
    assert((await figure.getAttribute('class')).includes('govdoc-media--center'), 'Soltar a imagem no centro não alterou sua posição.');
    await figure.locator('.govdoc-media-handle').scrollIntoViewIfNeeded();
    rootBox = await editorRoot.boundingBox();
    moveBox = await figure.locator('.govdoc-media-handle').boundingBox();
    moveX = moveBox.x + moveBox.width / 2;
    moveY = moveBox.y + moveBox.height / 2;
    await page.mouse.move(moveX, moveY);
    await page.mouse.down();
    await page.mouse.move(rootBox.x + rootBox.width * .16, moveY, { steps: 8 });
    assert((await page.locator('.govdoc-media-drop-zones').getAttribute('data-active-layout')) === 'wrap-left', 'Arraste não destacou a zona Texto à direita.');
    await page.mouse.up();
    assert((await figure.getAttribute('class')).includes('govdoc-media--wrap-left'), 'Soltar à esquerda não colocou o texto à direita.');
    assert(!(await page.locator('.govdoc-media-drop-zones').getAttribute('class')).includes('is-visible'), 'Zonas de soltura permaneceram sobre o editor.');
    await figure.locator('.govdoc-media-delete').click();
    assert(await figure.count() === 0, 'Exclusão pelo ícone na imagem não removeu o bloco.');
    assert(await page.locator('.govdoc-media-undo').isVisible(), 'Ação Desfazer não apareceu após a exclusão.');
    await page.screenshot({ path: 'tmp/article-delete-undo.png' });
    assert(!(await page.locator('#quill-editor-container .ql-editor').innerHTML()).includes(`document-media.php?id=${mediaId}`), 'Imagem excluída permaneceu no artigo.');
    await page.locator('.govdoc-media-undo button').click();
    assert(await figure.count() === 1 && (await figure.getAttribute('class')).includes('govdoc-media--wrap-left'), 'Desfazer não restaurou imagem e posição.');
    assert((await figure.locator('figcaption').innerText()) === 'Legenda ajustada', 'Desfazer não restaurou a legenda.');
    await figure.focus();
    await figure.press('Delete');
    assert(await figure.count() === 0, 'Tecla Delete não excluiu a imagem selecionada.');
    await page.locator('.govdoc-media-undo button').click();
    await figure.focus();
    await figure.press('Backspace');
    assert(await figure.count() === 0, 'Tecla Backspace não excluiu a imagem selecionada.');
    await page.locator('.govdoc-media-undo button').click();
    await page.locator('[data-media-remove]').click();
    assert(await figure.count() === 0, 'Botão Excluir imagem no painel não removeu o bloco.');
    await page.locator('.govdoc-media-undo button').click();
    assert(await figure.count() === 1, 'Desfazer no painel não restaurou a imagem.');
    await page.locator('#quill-editor-container .ql-editor p').last().click();
    await figure.focus();
    await figure.press('Enter');
    assert(await page.locator('#article-selected-media').isVisible(), 'Seleção por teclado não abriu os ajustes.');
    console.log('[OK] Quatro alças, proporção, arraste vertical e três zonas horizontais com prévia.');
    await page.locator('#article-video-url').fill('https://www.youtube.com/watch?v=tvnAs_Y0VT8');
    await page.locator('#article-insert-video').click();
    assert(await page.locator('#quill-editor-container .ql-editor iframe[src="https://www.youtube-nocookie.com/embed/tvnAs_Y0VT8"]').count() === 1, 'Vídeo não foi inserido no artigo.');
    const videoFigure = page.locator('#quill-editor-container .ql-editor figure.govdoc-media').filter({ has: page.locator('iframe') });
    await videoFigure.click();
    assert((await page.locator('[data-media-kind]').innerText()) === 'Vídeo selecionado', 'O editor não reconheceu o bloco de vídeo.');
    assert((await page.locator('[data-media-remove-label]').innerText()) === 'Excluir vídeo', 'A exclusão não identifica o tipo de mídia.');
    await videoFigure.locator('.govdoc-media-delete').click();
    assert(await videoFigure.count() === 0, 'Exclusão pelo ícone não removeu o vídeo.');
    await page.locator('.govdoc-media-undo button').click();
    assert(await videoFigure.count() === 1, 'Desfazer não restaurou o vídeo.');
    console.log('[OK] Exclusão de imagem/vídeo pelo bloco, painel e teclado, com Desfazer.');
    await videoFigure.click();
    await page.locator('[data-media-layout="wrap-right"]').click();
    assert((await videoFigure.getAttribute('class')).includes('govdoc-media--wrap-right'), 'Texto à esquerda do vídeo não aplicado.');
    const submittedHtml = await page.evaluate(() => {
      const form = document.getElementById('document-form');
      form.addEventListener('submit', event => event.preventDefault(), { once: true });
      form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
      return document.getElementById('text-content-input').value;
    });
    assert(submittedHtml.includes(`src="document-media.php?id=${mediaId}"`), 'URL de imagem não foi normalizada para a visualização.');
    assert(submittedHtml.includes('youtube-nocookie.com/embed/tvnAs_Y0VT8'), 'Vídeo não foi serializado.');
    const plainText = await page.evaluate(html => {
      const node = document.createElement('div'); node.innerHTML = html;
      node.querySelectorAll('figure.govdoc-media').forEach(figure => figure.remove());
      return node.textContent;
    }, submittedHtml);
    const missingText = ['Antes da', 'mídia aqui', 'Segundo parágrafo', 'Terceiro parágrafo'].filter(value => !plainText.includes(value));
    assert(missingText.length === 0, `Mover ou alinhar a mídia removeu trechos de texto: ${JSON.stringify({ missingText, plainText })}`);
    assert(!submittedHtml.includes('govdoc-media-handle') && !submittedHtml.includes('govdoc-media-resize-handle') && !submittedHtml.includes('govdoc-media-delete'), 'Controles do editor vazaram para o conteúdo publicado.');
    assert(!submittedHtml.includes('tabindex="0"'), 'Atributos de edição vazaram para o conteúdo publicado.');
    const htmlBase64 = Buffer.from(submittedHtml, 'utf8').toString('base64');
    const sanitizedBase64 = runPhp(`require 'services/RichTextSanitizer.php'; echo base64_encode(RichTextSanitizer::sanitize(base64_decode('${htmlBase64}', true)));`);
    const sanitizedHtml = Buffer.from(sanitizedBase64, 'base64').toString('utf8');
    assert(sanitizedHtml.includes('govdoc-media--wrap-left') && sanitizedHtml.includes('govdoc-media-frame') && sanitizedHtml.includes(`width: ${finalWidth}%`), 'Servidor não preservou o layout seguro.');
    assert(sanitizedHtml.includes('Legenda ajustada'), 'Servidor não preservou a legenda.');
    const reopened = await page.evaluate(html => {
      const host = document.createElement('div'); document.body.append(host);
      const editor = new Quill(host, { theme: 'snow' });
      editor.clipboard.dangerouslyPasteHTML(html.replace(/src=(["'])document-media\.php\?id=(\d+)\1/g, 'src=$1../document-media.php?id=$2$1'), 'silent');
      const figure = editor.root.querySelector('figure.govdoc-media');
      const result = { layout: figure?.className, width: figure?.style.width, caption: figure?.querySelector('figcaption')?.textContent, handles: figure?.querySelectorAll('.govdoc-media-resize-handle').length, videos: editor.root.querySelectorAll('figure.govdoc-media iframe').length };
      host.remove(); return result;
    }, sanitizedHtml);
    assert(reopened.layout.includes('govdoc-media--wrap-left') && reopened.width === `${finalWidth}%` && reopened.caption === 'Legenda ajustada' && reopened.handles === 4 && reopened.videos === 1, `Reabertura perdeu o layout: ${JSON.stringify(reopened)}`);
    console.log('[OK] HTML sanitizado e reaberto mantém posição, tamanho, legenda e vídeo.');
    const mediaResponse = await page.request.get(new URL(source, page.url()).href);
    assert(mediaResponse.status() === 200 && mediaResponse.headers()['content-type'] === 'image/png', 'Imagem privada não foi servida ao editor.');
    const anonymous = await browser.newContext();
    assert((await anonymous.request.get(new URL(source, page.url()).href)).status() === 401, 'Visitante anônimo conseguiu acessar imagem privada.');
    await anonymous.close();
    assert(errors.length === 0, `Erros JavaScript: ${errors.join('; ')}`);
    console.log('[OK] Editor de artigo, imagem inline, legenda, vídeo e controle de acesso.');
    await page.setViewportSize({ width: 390, height: 844 });
    if (!(await page.locator('#sidebar-menu').getAttribute('class')).includes('-translate-x-full')) {
      await page.locator('#sidebar-menu button[onclick="toggleMobileSidebar()"]').click();
    }
    await page.waitForFunction(() => document.getElementById('sidebar-menu').getBoundingClientRect().right <= 1);
    assert(await page.locator('#article-insert-image').isVisible(), 'Inserção de imagem desapareceu no celular.');
    assert(await page.locator('#article-insert-video').isVisible(), 'Inserção de vídeo desapareceu no celular.');
    await page.locator('#article-media-tools').scrollIntoViewIfNeeded();
    const mobileMetrics = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, scrollX, sidebar: document.getElementById('sidebar-menu').getBoundingClientRect().right, inspector: document.getElementById('article-selected-media').getBoundingClientRect().toJSON(), buttons: Array.from(document.querySelectorAll('#article-selected-media button')).map(button => ({ text: button.textContent, right: button.getBoundingClientRect().right })) }));
    assert(mobileMetrics.scrollWidth <= mobileMetrics.width, 'O editor criou rolagem horizontal no celular.');
    assert(mobileMetrics.inspector.right <= mobileMetrics.width + 1, `Ajustes de mídia cortados no celular: ${JSON.stringify(mobileMetrics)}`);
    assert(mobileMetrics.buttons.every(button => button.right <= mobileMetrics.width + 1), `Botão de mídia cortado no celular: ${JSON.stringify(mobileMetrics)}`);
    await page.screenshot({ path: 'tmp/mixed-article-editor-mobile.png' });
    console.log('[OK] Controles de mídia visíveis em largura móvel.');

    const verified = runPhp(`
require 'config/db.php'; require 'services/DocumentInlineMediaService.php'; require 'services/RichTextSanitizer.php';
$row = $pdo->query("SELECT id, uploaded_by FROM document_inline_media WHERE id = ${mediaId}")->fetch(PDO::FETCH_ASSOC);
if (!$row || !$row['uploaded_by']) throw new RuntimeException('Upload não foi registrado.');
$html = RichTextSanitizer::sanitize('<p>Texto</p><p><img src="document-media.php?id=${mediaId}" alt="Teste"></p><p>Legenda</p>');
if (!str_contains($html, 'document-media.php?id=${mediaId}')) throw new RuntimeException('Sanitizador removeu imagem válida.');
$video = RichTextSanitizer::sanitize('<iframe class="ql-video" src="https://www.youtube-nocookie.com/embed/tvnAs_Y0VT8"></iframe><iframe src="https://evil.example/embed/tvnAs_Y0VT8"></iframe>');
if (!str_contains($video, 'youtube-nocookie.com') || str_contains($video, 'evil.example')) throw new RuntimeException('Filtro de vídeo incorreto.');
$unsafe = RichTextSanitizer::sanitize('<figure class="govdoc-media govdoc-media--wrap-left" style="width: 9999%; position: absolute" onclick="alert(1)"><img src="document-media.php?id=${mediaId}" onerror="alert(1)"></figure>');
if (str_contains($unsafe, '9999%') || str_contains($unsafe, 'absolute') || str_contains($unsafe, 'onerror') || str_contains($unsafe, 'onclick')) throw new RuntimeException('Layout inseguro passou pela higienização.');
$pdo->beginTransaction();
$service = new DocumentInlineMediaService($pdo, __DIR__);
try { $service->bindReferenced(169, (int)$row['uploaded_by'] + 999999, $html); throw new RuntimeException('Upload de outro usuário foi aceito.'); } catch (InvalidArgumentException) {}
$service->bindReferenced(169, (int)$row['uploaded_by'], $html);
$bound = $pdo->query("SELECT document_id FROM document_inline_media WHERE id = ${mediaId}")->fetchColumn();
if ((int)$bound !== 169) throw new RuntimeException('Vínculo ao documento falhou.');
$removed = $service->removeUnreferenced(169, '<p>Imagem removida</p>');
if (count($removed) !== 1) throw new RuntimeException('Limpeza de imagem retirada do artigo falhou.');
$pdo->rollBack();
echo 'ok';
`);
    assert(verified === 'ok', 'Persistência de imagem não validada.');
    console.log('[OK] Higienização e vínculo transacional validados sem alterar documento real.');
    await page.setViewportSize({ width: 1280, height: 720 });
    await videoFigure.click();
    await page.locator('[data-media-remove]').click();
    assert(await page.locator('.govdoc-media-undo').isVisible(), 'Desfazer não apareceu após nova exclusão.');
    await page.evaluate(() => {
      const editor = Quill.find(document.getElementById('quill-editor-container'));
      editor.insertText(editor.getLength() - 1, 'Nova edição', 'user');
    });
    assert(!(await page.locator('.govdoc-media-undo').isVisible()), 'Desfazer deveria desaparecer após outra edição.');
    await page.close();
  } finally {
    await browser.close();
    if (mediaId > 0) runPhp(`
require 'config/db.php'; require 'services/DocumentInlineMediaService.php';
$stmt = $pdo->prepare('DELETE FROM document_inline_media WHERE id = ? AND document_id IS NULL RETURNING stored_filename');
$stmt->execute([${mediaId}]);
$name = $stmt->fetchColumn();
if ($name) (new DocumentInlineMediaService($pdo, __DIR__))->removeStoredFile((string)$name);
`);
    runPhp(`session_id('${session}'); session_start(); session_destroy();`);
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
